class Messages:
    LOGIN_SUCCESS = "Login successful."
    LOGOUT_SUCCESS = "Logout successful."
    TOKEN_REFRESHED = "Token refreshed successfully."
    INVALID_CREDENTIALS = "Invalid username or password."
    INCIDENT_CREATED = "Incident created successfully."

    USER_NOT_FOUND = "User not found."
    CURRENT_USER_RETRIEVED = "Current user retrieved successfully."
    USER_INACTIVE = "This account is inactive."
    ACCESS_DENIED = "You do not have permission to perform this action."
    USER_CREATED = "User created successfully."
    USER_UPDATED = "User updated successfully."
    USER_DELETED = "User deleted successfully."
    USER_ACTIVATED = "User activated successfully."
    USER_DEACTIVATED = "User deactivated successfully."
    USERNAME_ALREADY_EXISTS = "Username already exists."
    USER_FETCHED = "User retrieved successfully."
    USERS_FETCHED = "Users retrieved successfully."

    ADMIN_CREATION_NOT_ALLOWED = "Administrator accounts cannot be created."
    ADMIN_PROMOTION_NOT_ALLOWED = "Users cannot be promoted to administrator."
    ADMIN_ROLE_CHANGE_NOT_ALLOWED = "Administrator role cannot be changed."
    ADMIN_DEACTIVATION_NOT_ALLOWED = "Administrator account cannot be deactivated."
    ADMIN_DELETION_NOT_ALLOWED = "Administrator account cannot be deleted."

    WEBSITE_ALREADY_EXISTS = "Website already exists."
    WEBSITE_NOT_FOUND = "Website not found."
    WEBSITE_FETCHED = "Website fetched successfully."
    WEBSITES_FETCHED = "Websites fetched successfully."
    WEBSITE_ACTIVATED = "Website activated successfully."
    WEBSITE_DEACTIVATED = "Website deactivated successfully."
    WEBSITE_CREATED = "Website created successfully."
    WEBSITE_UPDATED = "Website updated successfully."
    WEBSITE_DELETED = "Website deleted successfully."
    WEBSITE_URL_EXISTS = "Website URL already exists."

    DASHBOARD_FETCHED = "Dashboard summary retrieved successfully."