class Collections:
    USERS = "users"
    MONITORS = "monitors"
    INCIDENTS = "incidents"
    STATUS_HISTORY = "status_history"
    HTTP_MONITORS = "http_monitors"
    INCIDENTS = "incidents"
    MONITOR_RESULTS = "monitor_results"
    MONITOR_STATES = "monitor_states"
    API_MONITORS = "api_monitors"